from datastructure.doublylinkedlist.doublylinkedlist import DoublyLinkedList

if __name__ == '__main__':
    doubly_linked_list = DoublyLinkedList()
    print(doubly_linked_list)
    doubly_linked_list.bulk_append(["A", "B", "C", "D", "E", "F"])
    print(doubly_linked_list)
    print("Head Next Data", doubly_linked_list.as_list()[0].next.data)
    print("Head Previous", doubly_linked_list.as_list()[0].previous)
    print("Tail Next", doubly_linked_list.as_list()[-1].next)
    print("Tail Previous Data", doubly_linked_list.as_list()[-1].previous.data)
    doubly_linked_list.add_node_after("G", "H")
    print(doubly_linked_list)
    doubly_linked_list.add_node_after("F", "G")
    print(doubly_linked_list)
    print("Head Next Data", doubly_linked_list.as_list()[0].next.data)
    print("Head Previous", doubly_linked_list.as_list()[0].previous)
    print("Tail Next", doubly_linked_list.as_list()[-1].next)
    print("Tail Previous Data", doubly_linked_list.as_list()[-1].previous.data)
    doubly_linked_list.add_node_before("0", "K")
    print(doubly_linked_list)
    doubly_linked_list.add_node_before("G", "GG")
    print(doubly_linked_list)
    print("Head Next Data", doubly_linked_list.as_list()[0].next.data)
    print("Head Previous", doubly_linked_list.as_list()[0].previous)
    print("Tail Next", doubly_linked_list.as_list()[-1].next)
    print("Tail Previous Data", doubly_linked_list.as_list()[-1].previous.data)
    doubly_linked_list.delete_node_by_key("GG")
    print(doubly_linked_list)
    doubly_linked_list.delete_node_by_key("GG")
    print(doubly_linked_list)
    doubly_linked_list.delete_node_by_key("A")
    print("After A deletion", doubly_linked_list)
    print("Head Next Data", doubly_linked_list.as_list()[0].next.data)
    print("Head Previous", doubly_linked_list.as_list()[0].previous)
    doubly_linked_list.delete_node_by_key("G")
    print("After G deletion", doubly_linked_list)
    print("Tail Next", doubly_linked_list.as_list()[-1].next)
    print("Tail Previous Data", doubly_linked_list.as_list()[-1].previous.data)
    doubly_linked_list.reverse()
    print("After reversing", doubly_linked_list)
    print("New Head Previous", doubly_linked_list.as_list()[0].previous)
    print("New Head Next Data", doubly_linked_list.as_list()[0].next.data)
    print("New 1 Previous", doubly_linked_list.as_list()[1].previous.data)
    print("New 1 Next Data", doubly_linked_list.as_list()[1].next.data)
    print("New 2 Previous", doubly_linked_list.as_list()[2].previous.data)
    print("New 2 Next Data", doubly_linked_list.as_list()[2].next.data)
    print("New 3 Previous", doubly_linked_list.as_list()[3].previous.data)
    print("New 3 Next Data", doubly_linked_list.as_list()[3].next.data)
    print("New Tail Next", doubly_linked_list.as_list()[-1].next)
    print("New Tail Previous Data", doubly_linked_list.as_list()[-1].previous.data)
    doubly_linked_list.bulk_append(["D", "E", "F"])
    print(doubly_linked_list)
    doubly_linked_list.remove_duplicates()
    print(doubly_linked_list)
    print("Head Next Data", doubly_linked_list.as_list()[0].next.data)
    print("Head Previous", doubly_linked_list.as_list()[0].previous)
    print("Tail Next", doubly_linked_list.as_list()[-1].next)
    print("Tail Previous Data", doubly_linked_list.as_list()[-1].previous.data)
