from circularlinkedlist import CircularLinkedList

if __name__ == '__main__':
    circular_linked_list = CircularLinkedList()
    circular_linked_list.print_list()
    circular_linked_list.remove_node_with_data("H")
    print("Tail Node:", circular_linked_list.tail_node())
    circular_linked_list.append("A")
    circular_linked_list.print_list()
    circular_linked_list.append("B")
    circular_linked_list.print_list()
    print("Tail Node data:", circular_linked_list.tail_node().data)
    circular_linked_list.prepend("0")
    circular_linked_list.print_list()
    circular_linked_list.remove_node_with_data("0")
    circular_linked_list.print_list()
    circular_linked_list.append("C")
    circular_linked_list.append("D")
    circular_linked_list.append("E")
    circular_linked_list.print_list()
    (a, b) = circular_linked_list.split_list()
    print(a)
    print(b)